"""Generate a battle map plan (and its DM key), then optionally forge it.

    python DM/forge/generate.py city --name "Fireholm Lower Quarter" --size 80x80 --seed 7 --forge
    python DM/forge/generate.py city --size 60x40 --density 0.5 --canal --wall

Writes DM/maps/<slug>/plan.txt and key.json. key.json numbers every building and square with its rooms,
starter loot you can use as it is, and empty slots for read-aloud text, events and creatures (Claude fills
those in when you press "Stock this map" in the DM site).
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))  # the application's modules
import campaign

GENERATORS = {
    'city': dict(module='gen_city', theme='city', title='City district', darkness=0.15),
}

STARTER_LOOT = {  # plain, rollable, so a map is usable before anyone writes anything clever
    'house': ['Purse under the mattress: 2d6 sp', 'Kitchen knives, a copper pot, a week of food'],
    'shop': [
        'Stock of the trade, about 3d10 x 10 gp all told (heavy, sells for half)',
        'Strongbox under the counter: 3d6 gp, 4d10 sp (DC 13 lock)',
    ],
    'tavern': [
        'Till: 4d10 sp, 2d6 gp',
        'Cellar: 12 kegs of ale, 3 casks of wine (10 gp each)',
        "Lost-property box: a stranger's cloak, a lucky die",
    ],
    'temple': [
        'Offering bowl: 3d10 cp, 2d6 sp',
        'Pair of silver candlesticks (25 gp each)',
        'Healing salves: 2 potions of healing in the vestry',
    ],
    'smithy': [
        '1d4 finished weapons (longsword, spear, mace)',
        "Smith's tools; 40 lb of iron bar",
        'Cashbox: 2d10 gp',
    ],
    'guardhouse': [
        'Key ring for the cells and the gate',
        '2 light crossbows, 40 bolts',
        'Arrest warrants and a wanted poster (who is on it?)',
    ],
    'warehouse': [
        'Crated cargo, 2d6 x 50 gp in bulk goods (dyes, wool, salt fish)',
        'Ledger showing a shipment that never arrived',
    ],
    'tower': ['Signal horn, a lantern, 1d4 torches'],
}


def slugify(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')[:48] or 'map'


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument('type', choices=sorted(GENERATORS))
    ap.add_argument('--name')
    ap.add_argument('--slug')
    ap.add_argument('--size', default='60x60', help='WIDTHxHEIGHT in 5 ft squares, 20 to 160 each')
    ap.add_argument('--seed', type=int, default=None)
    ap.add_argument('--cell', type=int, default=150)
    ap.add_argument('--darkness', type=float)
    ap.add_argument('--density', type=float, default=0.75)
    ap.add_argument('--alleys', type=float, default=0.6)
    ap.add_argument('--canal', action='store_true')
    ap.add_argument('--wall', action='store_true')
    ap.add_argument('--no-market', action='store_true')
    ap.add_argument('--summary', default='')
    ap.add_argument('--session', default='', help='prep document this map is for, e.g. s61')
    ap.add_argument('--forge', action='store_true', help='forge the map straight away')
    ap.add_argument('--jobs', type=int)
    a = ap.parse_args()
    m = re.fullmatch(r'(\d+)x(\d+)', a.size)
    if not m:
        sys.exit('size must look like 80x60')
    W, H = int(m.group(1)), int(m.group(2))
    if not (20 <= W <= 160 and 20 <= H <= 160):
        sys.exit('each side must be between 20 and 160 squares')
    spec = GENERATORS[a.type]
    seed = a.seed if a.seed is not None else int.from_bytes(os.urandom(3), 'big')
    name = a.name or f'{spec["title"]} {seed}'
    slug = slugify(a.slug or name)
    here = campaign.active()
    folder = here.map_folder(slug)
    if os.path.exists(folder):
        sys.exit(
            f'DM/maps/{slug} already exists; choose a different name to preserve its plan and DM key'
        )
    params = dict(
        density=max(0.1, min(1.0, a.density)),
        alleys=max(0.0, min(1.0, a.alleys)),
        canal=a.canal,
        wall=a.wall,
        market=not a.no_market,
    )
    print(f'generating {a.type} {W}x{H}, seed {seed}...', flush=True)
    gen = __import__(spec['module'])
    grid, areas = gen.generate(W, H, seed, **params)
    for area in areas:
        area['loot'] = [
            dict(item=x, where='', value='', source='starter')
            for x in STARTER_LOOT.get(area['kind'], [])
        ]
    os.makedirs(folder)
    head = [
        f'# Generated by Map Forge ({a.type}); safe to hand-edit, then re-forge.',
        f'name: {name}',
        f'theme: {spec["theme"]}',
        f'cell: {a.cell}',
        f'seed: {seed}',
        f'darkness: {a.darkness if a.darkness is not None else spec["darkness"]}',
        f'summary: {a.summary or f"{W}x{H} {a.type}: " + ", ".join(k for k, v in params.items() if v is True)}',
    ]
    with open(os.path.join(folder, 'plan.txt'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(head) + '\n---\n' + grid + '\n')
    key = dict(
        map=name,
        generator=a.type,
        params=dict(params, size=[W, H], seed=seed),
        session=a.session,
        areas=areas,
        events=[],
        notes='',
        stocked=False,
    )
    with open(os.path.join(folder, 'key.json'), 'w', encoding='utf-8', newline='\n') as f:
        json.dump(key, f, ensure_ascii=False, indent=1)
    kinds = {}
    for x in areas:
        kinds[x['kind']] = kinds.get(x['kind'], 0) + 1
    print(
        f'plan: DM/maps/{slug}/plan.txt  ({", ".join(f"{v} {k}" for k, v in sorted(kinds.items()))})',
        flush=True,
    )
    if a.forge:
        import forge

        forge.forge(os.path.join(folder, 'plan.txt'), True, a.jobs, here)
    print(f'SLUG {slug}', flush=True)


if __name__ == '__main__':
    main()
